### ISSUE TITLE
Project system crash with items that have Link metadata defined using recursive path properties

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1041]
Attempt to use a wildcard to include source files in a shared folder, and to set the `Link` metadata to control how they appear in the project tree, like this:

```xml
    <Compile Include="..\..\Shared\**\*.cs">
      <NeedsLink>true</NeedsLink>
    </Compile>
    <Compile Update="@(Compile)">
      <Link Condition="'%(NeedsLink)' == 'true'">%(RecursiveDir)\%(Filename)%(Extension)</Link>
    </Compile>
```

Repro project: [LinkMetadataRepro.zip](https://github.com/dotnet/roslyn-project-system/files/673392/LinkMetadataRepro.zip)

- Open project

EXPECTED: Project opens successfully
ACTUAL: Project system has encountered an error:

```
Recoverable
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.EnsureNotFaultedTree(IProjectVersionedValue`1 appliedValue)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.<PublishTreeAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.<PublishLatestTreeAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<RefreshAllSccIconsAsync>d__592.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<RefreshAllSccIconsIfNotCurrentlyInProgressAsync>d__566.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.EnsureNotFaultedTree(IProjectVersionedValue`1 appliedValue)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.<PublishTreeAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.<PublishLatestTreeAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<RefreshAllSccIconsAsync>d__592.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<RefreshAllSccIconsIfNotCurrentlyInProgressAsync>d__566.MoveNext()<---
```

**Comment by srivatsn** [comment]
@lifengl @jviau @adrianvmsft sounds like a CPS issue?

**Comment by lifengl** [comment]
This scenario is not supported at this moment.

Sent from my phone

On Dec 29, 2016, at 4:41 AM, Srivatsn Narayanan <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://github.com/lifengl> @jviau<https://github.com/jviau> @adrianvmsft<https://github.com/adrianvmsft> sounds like a CPS issue?

-

**Comment by dsplaisted** [comment]
@lifengl Is there any way to include files outside the project directory without listing each one in the project file, and have them display nicely in the project tree?

**Comment by davkean** [comment]
@lifengl Can we not crash in this case though?

**Comment by lifengl** [comment]
Of course, we should not crash.

Sent from my phone

On Dec 29, 2016, at 7:20 AM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://github.com/lifengl> Can we not crash in this case though?

-

**Comment by lifengl** [comment]
It is in our backlog.

Calculating link metadata through some msbuild ways might provide a workaround for now, which is what you tried.

I am not sure why you hit the exception.  It could be some items mapped to the same path and causing conflicts, which we don't handle well.

But our code doesn't handle the project you created in this way, when the user manipulates the project, and may corrupt the project at that point, so overall this is not supported.

Sent from my phone

On Dec 29, 2016, at 7:08 AM, Daniel Plaisted <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://github.com/lifengl> Is there any way to include files outside the project directory without listing each one in the project file, and have them display nicely in the project tree?

**Comment by drieseng** [comment]
For me, this works fine:

```xml
<Compile Include="..\Renci.SshNet\**\*.cs" Exclude="..\Renci.SshNet\Properties\AssemblyInfo.cs">
  <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
</Compile>
```

The only issue I have is that any folder that is recursively linked is marked as deleted:

![image](https://cloud.githubusercontent.com/assets/312863/21653200/42827faa-d2b0-11e6-989a-5dee1e3f0805.png)

To reproduce, open the **Renci.SshNet.VS2017** solution in https://github.com/sshnet/SSH.NET/commit/d95276d8614a503309c7248f99e233bdea3bb4bb and expand the **Renci.SshNet.NETCore** project.

**Comment by lifengl** [comment]
I see the link file feature expects to link an external file to an existing folder.  There is no virtual folder node concept for file links today.

Sent from my phone

On Jan 5, 2017, at 2:05 AM, Gert Driesen <notifications@github.com<mailto:notifications@github.com>> wrote:


For me, this works fine:

<Compile Include="..\Renci.SshNet\**\*.cs" Exclude="..\Renci.SshNet\Properties\AssemblyInfo.cs">
  <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
</Compile>

The only issue I have is that any folder that is recursively linked is marked as deleted:

[image]<https://cloud.githubusercontent.com/assets/312863/21653200/42827faa-d2b0-11e6-989a-5dee1e3f0805.png>

To reproduce, open the Renci.SshNet.VS2017 solution in sshnet/SSH.NET@d95276d<https://github.com/sshnet/SSH.NET/commit/d95276d8614a503309c7248f99e233bdea3bb4bb> and expand the Renci.SshNet.NETCore project.

-

**Comment by srivatsn** [comment]
This has been fixed in CPS. I verified on the latest build that the attached repro project loads fine.
