### ISSUE TITLE
Cannot open a shared project on d15rel 26110.1 without installing netcore tools

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn-project-system#1142]
**Repro**
Install d15rel 26110.1 only selecting the Managed Desktop and VSSDK workloads.
Attempt to open a solution containing a shared project

**Result**
Two warning dialogs will appear and the shared project will say `(incompatible) - The application is not installed.`

![microsoftteams-image](https://cloud.githubusercontent.com/assets/10487869/21864924/b4ce9fec-d7f8-11e6-801b-9c8388b6bbbd.png)
![microsoftteams-image 1](https://cloud.githubusercontent.com/assets/10487869/21864923/b4caf2c0-d7f8-11e6-85f4-356228cfdbe4.png)
![microsoftteams-image 2](https://cloud.githubusercontent.com/assets/10487869/21864922/b4cae58c-d7f8-11e6-8954-58d1cf10f603.png)

The ActivityLog shows the following exception:
```
LegacySitePackage failed for package [Microsoft.VisualStudio.ProjectSystem.VS.Implementation.SharedProjectFilesPackage.SharedProjectFilesPackage, Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]
Source: 'Microsoft.VisualStudio.Composition'
Description: Import "Microsoft.VisualStudio.ProjectSystem.ProjectServiceHost.ProjectCollection" could not be satisfied.
Microsoft.VisualStudio.Composition.CompositionFailedException: Import "Microsoft.VisualStudio.ProjectSystem.ProjectServiceHost.ProjectCollection" could not be satisfied.
 ---> Microsoft.VisualStudio.Composition.CompositionFailedException: Value exported from "Microsoft.VisualStudio.ProjectSystem.MultithreadedProjectCollectionHost.ProjectCollection" cannot be assigned to import site "Microsoft.VisualStudio.ProjectSystem.ProjectServiceHost.ProjectCollection". 
          at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.ThrowIfExportedValueIsNotAssignableToImport(RuntimeImport import, RuntimeExport export, Object exportedValue) 
          at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import) 
          at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
 --- End of inner exception stack trace --- 
    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports() 
    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.SatisfyImmediateImports() 
    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState) 
    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose() 
    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass13_0.<CreateExportFactory>b__0() 
    at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0() 
    at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0() 
    at System.Composition.ExportFactory`1.CreateExport() 
    at Microsoft.VisualStudio.ProjectSystem.ProjectServiceAccessor.CreateMultithreadedCpsService() 
    at Microsoft.VisualStudio.ProjectSystem.ProjectServiceAccessor.<.ctor>b__6_0() 
    at System.Lazy`1.CreateValue() --- End of stack trace from previous location where exception was thrown --- 
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Lazy`1.get_Value() 
    at Microsoft.VisualStudio.ProjectSystem.ProjectServiceAccessor.GetProjectService(ProjectServiceThreadingModel version) 
    at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.SharedProjectFilesPackage.SharedProjectFilesPackage.Initialize() 
    at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)Microsoft.VisualStudio.Composition.CompositionFailedException: Value exported from "Microsoft.VisualStudio.ProjectSystem.MultithreadedProjectCollectionHost.ProjectCollection" cannot be assigned to import site "Microsoft.VisualStudio.ProjectSystem.ProjectServiceHost.ProjectCollection". 
    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.ThrowIfExportedValueIsNotAssignableToImport(RuntimeImport import, RuntimeExport export, Object exportedValue) 
    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import) 
    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
```

**Comment by srivatsn** [comment]
@mattwar can you take a look at this?

**Comment by davkean** [comment]
Can't image what is causing this.

**Comment by srivatsn** [comment]
This looks like a MEF composition failure in CPS. @jviau is taking a look.

**Comment by jviau** [comment]
I am unable to repro this with the same build and a similar solution/project. 

@tannergooding 
I would like to look at your MEF cache files from %LocalAppData%\Microsoft\VisualStudio\15.0_{installId}\ComponentModelCache

After you have provided those can you run `devenv /updateConfiguration` and try opening again?

**Comment by srivatsn** [comment]
Closing since @jinujoseph verified that this doesn't repro
