### ISSUE TITLE
Errors opening test projects 

### ISSUE THREAD

**Issue by rynowak** [dotnet/roslyn-project-system#1145]
I get a bunch of errors opening a particular solution.

using VS from `int.d15rel` version `15.0.26110.0`

![image](https://cloud.githubusercontent.com/assets/1430011/21866745/4538d096-d800-11e6-9712-6d78e552b17b.png)

**Repro:**
git clone https://github.com/aspnet/Razor.git
cd Razor
.\build.cmd initialize
open Razor.sln in VS

All of the test projects fail to load when the solution is opened. Removing the test projects from the solution and adding them back manually causes them to behave normally.

Attached fault info from VS:
[VsProjectFault_5920ecfe-8090-4aa2-ba64-01192b2fd35b.failure.txt](https://github.com/dotnet/roslyn-project-system/files/700064/VsProjectFault_5920ecfe-8090-4aa2-ba64-01192b2fd35b.failure.txt)

**Comment by srivatsn** [comment]
The stack seems to be 

```
Recoverable
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.ResolveDependentItems(Dictionary`2 pendingItemsByDirectory)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<GenerateOriginalTreeAsync>d__117.MoveNext()
```

@lifengl @jviau @adrianvmsft does this look familiar?

**Comment by rynowak** [comment]
There's also another kind of error in there, but I'm not sure if it's just a consequence of the other failures
```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'EditAndContinue'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'EditAndContinue'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---
```

**Comment by adrianvmsft** [comment]
@srivatsn Yes, seems to be the same as #862. This crash is tracked with internal bug 362077
The 2nd issue (capability EditAndContinue) seems related to #1141

**Comment by srivatsn** [comment]
Both the issues mentioned above are fixed in RC3. Closing this. @rynowak please reopen if you are seeing this again.
