### ISSUE TITLE
xUnit Test Discovery Error

### ISSUE THREAD

**Issue by ardalis** [dotnet/roslyn-project-system#1221]
I have a test project that utilizes ASP.NET Core 1.1 and it's getting this error when trying to discover tests in Visual Studio.

[xUnit.net 00:00:00.0439643] Exception discovering tests: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetAvailableRunnerReporters(IEnumerable`1 sources)

   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetRunnerReporter(IEnumerable`1 assemblyFileNames)

   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IRunSettings runSettings, IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)

I talked to @bradwilson and he let me know to add the missing package as a reference to the test project, and this worked as a workaround.

Also posted here: http://ardalis.com/xunit-test-discovery-error-with-aspnet-core-1-1

**Comment by srivatsn** [comment]
Tagging @dotnet/vstest

**Comment by davkean** [comment]
This issue was moved to Microsoft/vstest#365
