### ISSUE TITLE
AV creating a new project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1349]
Build: 26126.1 D15PreRel

Hit an AV creating a new project:

```
Faulting application name: devenv.exe, version: 15.0.26126.1, time stamp: 0x588a7b86
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0x2820
Faulting application start time: 0x01d27844d72d1dd9
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe
Faulting module path: unknown
Report Id: 74c2dcbd-1c61-416f-a011-35ced7e0997d
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(System.Object, IntPtr, IntPtr ByRef, Boolean ByRef)
   at Microsoft.VisualStudio.Shell.Interop.IVsHierarchy.GetProperty(UInt32, Int32, System.Object ByRef)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectHostObject.GetProperty(UInt32, Int32, System.Object ByRef)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.ConfiguredProjectHostObject.GetProperty(UInt32, Int32, System.Object ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVsHierarchyExtensions.TryGetItemProperty[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, UInt32, Int32, System.__Canon ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryGetProjectData(Microsoft.CodeAnalysis.ProjectId, Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioHostProject ByRef, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy ByRef, EnvDTE.Project ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryGetDTEProject(Microsoft.CodeAnalysis.ProjectId)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessProjectChange(Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.ProjectId)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessBatchedChangesOnForeground(System.Threading.CancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService+<>c__DisplayClass26_0.<OnWorkspaceChanged>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Editor.Shared.Utilities.SynchronizationContextTaskScheduler.PostCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by davkean** [comment]
Also hit this when I added a new VB Winforms project to an existing solution containing .NET Core:

```
Exception Info: System.AccessViolationException
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame+MarshalingWindowFrame.Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.GetFramePos(Microsoft.VisualStudio.Shell.Interop.VSSETFRAMEPOS[], System.Guid ByRef, Int32 ByRef, Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at Microsoft.VisualStudio.Shell.Interop.IVsHierarchy.GetProperty(UInt32, Int32, System.Object ByRef)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.UnconfiguredProjectHostObject.GetProperty(UInt32, Int32, System.Object ByRef)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.ConfiguredProjectHostObject.GetProperty(UInt32, Int32, System.Object ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVsHierarchyExtensions.TryGetItemProperty[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, UInt32, Int32, System.__Canon ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryGetProjectData(Microsoft.CodeAnalysis.ProjectId, Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioHostProject ByRef, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy ByRef, EnvDTE.Project ByRef)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryGetDTEProject(Microsoft.CodeAnalysis.ProjectId)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessProjectChange(Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.ProjectId)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessBatchedChangesOnForeground(System.Threading.CancellationToken)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService+<>c__DisplayClass26_0.<OnWorkspaceChanged>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Editor.Shared.Utilities.SynchronizationContextTaskScheduler.PostCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by davkean** [comment]
@CyrusNajmabadi @mavasani @jviau Anyone recognize this?

**Comment by jviau** [comment]
@davkean yes I was investigating a feedback issue with a AV during `clr!SafeAddRef()` when casting the CPS IVsHierarchy. We are still investigating it, but it is possible a native extension is over-releasing our IVsHierarchy COM object.

**Comment by davkean** [comment]
I'm seeing lots more AVs in this build:
```
Exception Info: System.AccessViolationException
   at Microsoft.VisualStudio.Shell.Interop.IVsUIDataSource.UnadvisePropertyChangeEvents(UInt32)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.<UnsubscribeInnerSourcePropertyChangeEvents>b__59_0()
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.CallCatchingExceptions(System.Action)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.UnsubscribeInnerSourcePropertyChangeEvents()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSourceCollection+<>c__DisplayClass94_0.<DisposeChildItems>b__0()
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.CallCatchingExceptions(System.Action)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSourceCollection.DisposeChildItems()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSourceCollection.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSourceCollection.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSourceCollection.Dispose()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource+<>c__DisplayClass60_0.<DisposeCachedProperties>b__0()
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.CallCatchingExceptions(System.Action)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.DisposeCachedProperties()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSourceCollection+<>c__DisplayClass94_0.<DisposeChildItems>b__0()
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.CallCatchingExceptions(System.Action)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSourceCollection.DisposeChildItems()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSourceCollection.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSourceCollection.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSourceCollection.Dispose()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource+<>c__DisplayClass60_0.<DisposeCachedProperties>b__0()
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.CallCatchingExceptions(System.Action)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.DisposeCachedProperties()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource+<>c__DisplayClass60_0.<DisposeCachedProperties>b__0()
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.CallCatchingExceptions(System.Action)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.DisposeCachedProperties()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource+<>c__DisplayClass60_0.<DisposeCachedProperties>b__0()
   at Microsoft.Internal.VisualStudio.PlatformUI.Utilities.CallCatchingExceptions(System.Action)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.DisposeCachedProperties()
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSource.Dispose(Boolean)
   at Microsoft.Internal.VisualStudio.PlatformUI.DataSource+VsUIDataSourcePropertyChangeEvents.Disconnect(Microsoft.VisualStudio.Shell.Interop.IVsUISimpleDataSource)

```

**Comment by davkean** [comment]
@jviau how did we go with this?

**Comment by jviau** [comment]
@davkean how often are you seeing these? Do you have repro steps?

**Comment by davkean** [comment]
No repro steps, I just created the project in both cases. It didn't happen all the time, and I haven't hit it in newer builds.

**Comment by srivatsn** [comment]
CPS has checked in a fix for this.
