### ISSUE TITLE
ObjectDisposedException at DependenciesProjectTreeProvider.Dispose

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#1380]
Create a new dotnet core project, attach a debugger and close the solution

**Got:**
```
{"Cannot access a disposed object.\r\nObject name: 'Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScope'."}

   at Microsoft.Verify.NotDisposed(IDisposableObservable disposedValue, String message)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.EnsureInitialized(Boolean allowInitializing)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScopeBase.get_Current()
   at Microsoft.VisualStudio.ProjectSystem.CapabilitiesExtensions.GetEffectiveCapabilitiesSnapshot(IProjectCapabilitiesScope capabilitiesScope)
   at Microsoft.VisualStudio.ProjectSystem.OrderPrecedenceImportCollection`2.GetFilteredSnapshot()
   at Microsoft.VisualStudio.ProjectSystem.OrderPrecedenceImportCollection`2.GetEnumerator()
   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesProjectTreeProvider.Dispose(Boolean disposing) in c:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Tree\Dependencies\DependenciesProjectTreeProvider.cs:line 319
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.<DisposeAsync>b__17_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

This doesn't seem to be bring down VS though.

**Comment by srivatsn** [comment]
@davkean same as https://github.com/dotnet/roslyn-project-system/issues/1373?

**Comment by davkean** [comment]
Dup of #1373.
