### ISSUE TITLE
VS crash due to InvalidProjectFileException

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#1435]
D15PreRel 26130.00

1. Create new C# netcore application.
2. Edit the csproj to add the following property, which contains a new line:

```
<BaseIntermediateOutputPath>
      
</BaseIntermediateOutputPath>
```

**Got:** Many consecutive dialogs with following text:

```
---------------------------
Microsoft Visual Studio
---------------------------
The project 'ConsoleApp11' has encountered an error.  You may need reload the project after fixing the problem.

 

The expression "[System.IO.Path]::Combine(c:\users\mavasani\documents\visual studio 2017\Projects\ConsoleApp11\ConsoleApp11\, 

      

    \Release\netcoreapp1.0\Fakes)" cannot be evaluated. Illegal characters in path.  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Fakes\Microsoft.QualityTools.Testing.Fakes.targets
---------------------------
OK   
---------------------------
```

3. Open the project folder in windows explorer and delete the bin and obj folders.

**Got:** VS crash with following exception.

```
Microsoft.Build.Exceptions.InvalidProjectFileException: 'The expression "[System.IO.Path]::Combine(c:\users\mavasani\documents\visual studio 2017\Projects\ConsoleApp11\ConsoleApp11\, 

      

    \Debug\netcoreapp1.0\Fakes)" cannot be evaluated. Illegal characters in path.'

   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.PrepareResourceForConcurrentAccessAsync(Project resource, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterResourceLock`2.Helper.<.ctor>b__8_2(Task prev, Object state)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AsyncReaderWriterResourceLock`2.Helper.<GetResourceAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Properties.ProjectProperties.<GetEvaluatedPropertyValueAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageProperty.<GetValueAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageStringProperty.<GetValueAsStringAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageStringProperty.<GetValueAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher.<GetProjectLockFilePathAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher.<ProjectTree_ChangedAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by mavasani** [comment]
Not sure if this is a CPS issue or we need to handle invalid BaseIntermediateOutputPath better.

**Comment by davkean** [comment]
Think this is a general problem, errors during evaluation are leaking in a bunch of places:

https://github.com/dotnet/roslyn-project-system/issues/1408
https://github.com/dotnet/roslyn-project-system/issues/1394

CPS itself probably needs to more resilient to these.

**Comment by srivatsn** [comment]
Tag @lifengl is there anything we can do about this for RTM to avoid crashing VS?

**Comment by lifengl** [comment]
For this issue, maybe we can do some validation in the logic when it reloads the project:

•	Before reloading the project, persist the project xml into a temporary buffer,
•	Reload the project (maybe doing some simple verification for invalid Xml ?)
•	After reloading the project, going through all configured project loaded in the same unconfigured project and call lock.GetProjectAsync(configuredProject), which will force the project to be evaluated for that configuration.  If anything throws, it is an invalid project, so it can either unload the project, or restore the project with the buffer saved in the first step.
•	If all passed, release the write lock at that point. 
•	The rest of the project system will only see changes after that point
•	When the user switches to a new configuration, evaluation can still fail, but that is a known code path to handle this issue.

**Comment by davkean** [comment]
That sounds like a good approach.

Can a broken evaluation cause downstream issues that will be impossible to recover from?

**Comment by lifengl** [comment]
Today different code can read the project which triggers the evaluation:

•	For non-data flow code, which is typically triggered by an API call from other part of the VS (automation).  An exception will be thrown, and the method/operation can fail.  It is hard to know whether the code calling into it handles it correctly.  
•	For data flow code, the evaluation will cause data flow to be closed in the fault state.  That is not recoverable until the project is reloaded.

Maybe in the long run, a fault state should flow through the dataflow, instead of causing them to be closed, but it is difficult to change at this moment.

**Comment by lifengl** [comment]
Of course, if the verification is done within a same write lock, no other code will see the bad state, so no need to recover either.

**Comment by lifengl** [comment]
Also ProjectLock service GetProjectAsync() cannot eat the exception when the project file is invalid.  It looks like this common crash path is inside ProjectSystem.VS.ProjectLockFileWatcher.  Handling the error case here will not fix the problem, but may prevent the VS to crash immediately?

**Comment by davkean** [comment]
Dup'ing against a uber issue that is tracking this: https://github.com/dotnet/roslyn-project-system/issues/1570
