### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1454]
I have seen this error couple of times, random occasion while changing the TFM. 

![image](https://cloud.githubusercontent.com/assets/12449387/22573368/84210d1e-e95d-11e6-9168-9e2110fafbd6.png)

Logs here
\\mlangfs1\public\Jinuj\Log\ReportError 

Exception 

at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Microsoft.VisualStudio.Shell.Interop.IVsLanguageServiceBuildErrorReporter2.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider.<AddMessageCoreAsync>d__9.MoveNext()

**Build**
26201.1.d15rel

**Comment by davkean** [comment]
This is https://github.com/dotnet/roslyn/issues/16612.
