### ISSUE TITLE
System.ArgumentException at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalFile

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#1563]
Filing on behalf of Navin.

**Repro Steps**:
1. Clone github.com/microsoft/vstest 
2. run build.cmd
3. Then open TestPlatform.sln

It crashes it after few seconds. Below is the call stack.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalDocument(IVisualStudioHostDocument document, Boolean isCurrentContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalFile(String additionalFilePath, Func`2 getIsInCurrentContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.<>c__DisplayClass38_0.<AddAdditionalFile>b__0()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.<>c__DisplayClass13_0.<ExecuteForegroundAction>b__0(Task _)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass3_0.<SafeContinueWith>b__0(Task antecedent)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass7_0`1.<SafeContinueWith>b__0(Task t)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass7_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalDocument(Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioHostDocument, Boolean)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAdditionalFile(System.String, System.Func`2<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioHostDocument,Boolean>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject+<>c__DisplayClass38_0.<AddAdditionalFile>b__0()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject+<>c__DisplayClass13_0.<ExecuteForegroundAction>b__0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass3_0.<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass7_0`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWith>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Editor.Shared.Utilities.SynchronizationContextTaskScheduler.PostCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by mavasani** [comment]
I am unable to repro this D15Rel 26213.1

**Comment by jeremymeng** [comment]
I am hitting this on the latest build from int channel (D15Rel 26214.1)

**Comment by mavasani** [comment]
@jeremymeng do you have a repro project you can share?

**Comment by jeremymeng** [comment]
@mavasani sent via email

**Comment by jeremymeng** [comment]
My teammate mentioned that he did a clean install to 26214.1 and didn't experience the crash. I did upgrade from the VS Installer.

**Comment by mavasani** [comment]
Thanks, I got it to repro. Investigating now. @jeremymeng Did this solution open fine on older VS builds or you made some changes recently that is causing it to repro? Trying to figure out if this is a regression.

**Comment by jeremymeng** [comment]
@mavasani it is working fine on an earlier build (26207 or something).

**Comment by mavasani** [comment]
Thanks, I just confirmed the same. Looking what regressed..

**Comment by mavasani** [comment]
I confirmed the issue doesn't repro on D15Rel 26210.00, but repros consistently on 26213.1.

I investigated further and the root cause seems to be that CPS is now generating duplicate Design time build updates for the same project, with all the items (sources, references, additional files) listed as AddedItems in both the updates, and we don't handle duplicates. @lifengl @jviau this seems to be a recent CPS regression, can you investigate?

**Comment by lifengl** [comment]
Your code chains to multiple dataflows, including dataflow from different project configurations.  Duplicates are expected, because the delta is calculated in each dataflow alone.  You have to change your code to handle it.

**Comment by davkean** [comment]
We aren't merging data from different project configurations.

**Comment by lifengl** [comment]
Forgot to mention that the code subscribes both evaluation and design time build rules, and @mavasani verified that duplicated changes were from that side.
