### ISSUE TITLE
Any .settings designer crashes for net462 exe project

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-project-system#1799]
I'm still working on whittling down a repro. I'm just converting legacy to new csproj and fixing the disassociation of the .settings from the .designer.cs that comes with the manual conversion. I assume you just delete the .designer.cs and open the .settings and tell it to do codegen, because that works in brand new projects. However in the converted project, when you open the designer (either via the .settings file or via the project properties) the page shows only a Windows error icon and the message:

> Value cannot be null.
> Parameter name: key

Sometimes it shows

> Could not resolve mscorlib for target framework '.NETFramework,Version=v4.6.2'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.

With the message box:

> The project system has encountered an error.
> 
> Value cannot be null.
> Parameter name: key
> 
> A diagnostic log has been written to the following location: "%temp%\VsProjectFault_04bf065c-6a0b-478e-be15-5364f34d8b9b.failure.txt".

So here is VsProjectFault_04bf065c-6a0b-478e-be15-5364f34d8b9b.failure.txt:

```
=====================
3/20/2017 4:08:03 PM
Crippling
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.ProjectSystem.VS.References.DesignTimeAssemblyResolution.GetAllResolvedReferences()
   at Microsoft.VisualStudio.ProjectSystem.VS.References.DesignTimeAssemblyResolution.ResolveReferences(String[] originalNames, AssemblyName[] assemblyName, VsResolvedAssemblyPath[] assemblyPaths)
   at Microsoft.VisualStudio.ProjectSystem.VS.References.DesignTimeAssemblyResolution.ResolveAssemblyPathInTargetFx(String[] prgAssemblySpecs, UInt32 cAssembliesToResolve, VsResolvedAssemblyPath[] prgResolvedAssemblyPaths, UInt32& pcResolvedAssemblyPaths)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.ResolveAssemblyPath(String assemblySpec)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.ResolveAssembly(AssemblyName assemblyName)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetSystemAssembly()
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceAdded(Reference r)
   at VSLangProj._dispReferencesEvents_ReferenceAddedEventHandler.Invoke(Reference pReference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceAdded(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.VisualStudio.ProjectSystem.VS.References.DesignTimeAssemblyResolution.GetAllResolvedReferences()
   at Microsoft.VisualStudio.ProjectSystem.VS.References.DesignTimeAssemblyResolution.ResolveReferences(String[] originalNames, AssemblyName[] assemblyName, VsResolvedAssemblyPath[] assemblyPaths)
   at Microsoft.VisualStudio.ProjectSystem.VS.References.DesignTimeAssemblyResolution.ResolveAssemblyPathInTargetFx(String[] prgAssemblySpecs, UInt32 cAssembliesToResolve, VsResolvedAssemblyPath[] prgResolvedAssemblyPaths, UInt32& pcResolvedAssemblyPaths)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.ResolveAssemblyPath(String assemblySpec)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.ResolveAssembly(AssemblyName assemblyName)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetSystemAssembly()
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsDesignTimeAssemblyResolution projectAssemblyResolution, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsDesignTimeAssemblyResolution assemblyResolution, IDesignTimeAssemblyLoader assemblyLoader, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetTargetFrameworkProvider(IServiceProvider provider, IDesignTimeAssemblyLoader assemblyLoader, IVsHierarchy hierarchy, Object instance)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceAdded(Reference r)
   at VSLangProj._dispReferencesEvents_ReferenceAddedEventHandler.Invoke(Reference pReference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceAdded(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()<---

===================
```

I'll try to simplify to a repro. None of my guesses have worked yet and when I delete a bunch of the project and copy the project to a new folder, the problem disappears.

**Comment by jnm2** [comment]
I will say that https://developercommunity.visualstudio.com/content/problem/33158/cannot-use-the-main-or-any-right-click-menu-while.html becomes particularly onerous when reloading the solution over and over. I am not a bit happy with the lack of followup in the last four months.

**Comment by jnm2** [comment]
Oh hey, guess what. The problem goes away when I remove this section:

```xml
  <!-- Workaround for https://github.com/dotnet/roslyn-project-system/issues/1739 -->
  <PropertyGroup>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>
```

**Comment by jnm2** [comment]
Oh hey, guess what. The problem goes away when I remove this section:

Edit:

**Comment by jnm2** [comment]
No, it's something else. Hang on.

**Comment by jnm2** [comment]
Did not expect that. My repro is currently looking like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Another\Project.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
    </None>
  </ItemGroup>

</Project>
```

If the project reference is removed, the settings designer works. If the project reference is added, the designer starts crashing again.

On to simplifying the next project.

**Comment by jnm2** [comment]
Can't repro with fewer than three projects so far :D Still working.

**Comment by jnm2** [comment]
Well, I built up the repro from scratch and now I'm getting a new error message in place of the others:

> Object reference not set to an instance of an object

**Comment by jnm2** [comment]
Here's the complete repro:

 * Open the solution in https://github.com/jnm2/misc-codesamples/raw/master/Bug%20reports/.NET/Settings%20designer%20crash.zip
 * Open ConsoleAppWithSettings/Properties/Settings.settings in solution explorer or view the Settings section in ConsoleAppWithSettings properties.
 * See "Object reference not set to an instance of an object." No idea why that changed from "Could not resolve mscorlib for target framework '.NETFramework,Version=v4.6.2'. This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted." or "Value cannot be null. Parameter name: key" like it says on my original project, but you can probably take it from here.


The csprojs:

ConsoleAppWithSettings.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library1\Library1.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
    </None>
  </ItemGroup>

</Project>
```

Library1.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library2\Library2.csproj" />
  </ItemGroup>

</Project>
```

Library2.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by davkean** [comment]
Thanks @jnm2 and for your efforts to get a repro. We're [aware of this issue](https://github.com/dotnet/roslyn-project-system/issues/1718) and we've fixed this. It will be available in the next update.
