### ISSUE TITLE
VS 2017 displays an error window when solution opened with projects from the other folder than the folder with .sln

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn-project-system#1822]
![default](https://cloud.githubusercontent.com/assets/2365592/24167451/77c9dae0-0e7f-11e7-8f56-0c12a9cad344.png)

```
=====================
21.03.2017 21:25:25
Crippling
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An element with the same key but a different value already exists. Key: System.Xml.XPath
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectBuildSubscriptionService.UpdateRuleSnapshotCore(IProjectVersionedValue`1 source, String ruleName, IRule rule, ImmutableDictionary`2 items, ImmutableDictionary`2 properties, ImmutableList`1 recentItemRenames, IProjectChangeDiff& diff)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectRuleSubscriptionServiceBase`1.UpdateSnapshotCoreAsync(TSource source, IImmutableSet`1 subscribedElements, IProjectVersionedValue`1 previousResult)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<UpdateSnapshotAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<>c__DisplayClass27_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<<Initialize>b__27_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataflowExtensions.<>c__DisplayClass23_0`2.<<CreateSelfFilteringTransformBlock>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: An element with the same key but a different value already exists. Key: System.Xml.XPath
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectBuildSubscriptionService.UpdateRuleSnapshotCore(IProjectVersionedValue`1 source, String ruleName, IRule rule, ImmutableDictionary`2 items, ImmutableDictionary`2 properties, ImmutableList`1 recentItemRenames, IProjectChangeDiff& diff)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectRuleSubscriptionServiceBase`1.UpdateSnapshotCoreAsync(TSource source, IImmutableSet`1 subscribedElements, IProjectVersionedValue`1 previousResult)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<UpdateSnapshotAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<>c__DisplayClass27_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<<Initialize>b__27_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataflowExtensions.<>c__DisplayClass23_0`2.<<CreateSelfFilteringTransformBlock>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
```

**Comment by xperiandri** [comment]
Like in this `.sln`

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26228.4
MinimumVisualStudioVersion = 10.0.40219.1
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{AD54301D-735E-4F26-9D6A-38986A32B183}"
	ProjectSection(SolutionItems) = preProject
		NuGet.config = NuGet.config
	EndProjectSection
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HahaTaxi.Api", "src\HahaTaxi.Api\HahaTaxi.Api.csproj", "{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HahaTaxi.Data", "src\HahaTaxi.Data\HahaTaxi.Data.csproj", "{F34B9C8C-D5C6-4D70-91B8-514114B306F1}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HahaTaxi.Logging", "src\HahaTaxi.Logging\HahaTaxi.Logging.csproj", "{7A596BAC-2490-4294-A34B-67AB483A3280}"
EndProject
Project("{00D1A9C2-B5F0-4AF3-8072-F6C62B433612}") = "HahaTaxi.Database", "src\HahaTaxi.Database\HahaTaxi.Database.sqlproj", "{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HahaTaxi.SignalRClient", "src\HahaTaxi.SignalRClient\HahaTaxi.SignalRClient.csproj", "{54C347F5-C49A-4A87-A550-E1C934CCEDEC}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Swashbuckle.AspNetCore.Swagger", "..\..\GitHub\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.Swagger\Swashbuckle.AspNetCore.Swagger.csproj", "{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Swashbuckle.AspNetCore.SwaggerGen", "..\..\GitHub\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\Swashbuckle.AspNetCore.SwaggerGen.csproj", "{74F30AFC-2ED4-4C81-AE32-24141CCC242B}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Swashbuckle.AspNetCore.SwaggerUI", "..\..\GitHub\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerUI\Swashbuckle.AspNetCore.SwaggerUI.csproj", "{0438F390-BF4C-4B2F-8876-A242ADD19E21}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}.Release|Any CPU.Build.0 = Release|Any CPU
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1}.Release|Any CPU.Build.0 = Release|Any CPU
		{7A596BAC-2490-4294-A34B-67AB483A3280}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{7A596BAC-2490-4294-A34B-67AB483A3280}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{7A596BAC-2490-4294-A34B-67AB483A3280}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{7A596BAC-2490-4294-A34B-67AB483A3280}.Release|Any CPU.Build.0 = Release|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Debug|Any CPU.Deploy.0 = Debug|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Release|Any CPU.Build.0 = Release|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Release|Any CPU.Deploy.0 = Release|Any CPU
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC}.Release|Any CPU.Build.0 = Release|Any CPU
		{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}.Release|Any CPU.Build.0 = Release|Any CPU
		{74F30AFC-2ED4-4C81-AE32-24141CCC242B}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{74F30AFC-2ED4-4C81-AE32-24141CCC242B}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{74F30AFC-2ED4-4C81-AE32-24141CCC242B}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{74F30AFC-2ED4-4C81-AE32-24141CCC242B}.Release|Any CPU.Build.0 = Release|Any CPU
		{0438F390-BF4C-4B2F-8876-A242ADD19E21}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{0438F390-BF4C-4B2F-8876-A242ADD19E21}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{0438F390-BF4C-4B2F-8876-A242ADD19E21}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{0438F390-BF4C-4B2F-8876-A242ADD19E21}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(NestedProjects) = preSolution
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
		{7A596BAC-2490-4294-A34B-67AB483A3280} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
	EndGlobalSection
	GlobalSection(CodealikeProperties) = postSolution
		SolutionGuid = d1818a1b-51ed-4c07-8f41-441e0f4bdc1d
	EndGlobalSection
EndGlobal
```

Where SwashBuckle is located in the folder other that folder with `.sln` or subfolders

**Comment by davkean** [comment]
Thanks, this is known and dup of https://github.com/dotnet/roslyn-project-system/issues/1213, which we've opened an internal bug against the team that owns this.

**Comment by xperiandri** [comment]
Good to know, thanks
