### ISSUE TITLE
Project fault occasionally opening a project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#301]
Get this occasionally opening some large projects:

```
=====================
7/14/2016 3:35:38 PM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.ProjectSystem.AppDesignerFolderProjectTreePropertiesProvider.AreContentsVisibleOnlyInShowAllFiles(IImmutableDictionary`2 projectTreeSettings) in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\AppDesignerFolderProjectTreePropertiesProvider.cs:line 83
   at Microsoft.VisualStudio.ProjectSystem.AbstractSpecialFolderProjectTreePropertiesProvider.CalculatePropertyValues(IProjectTreeCustomizablePropertyContext propertyContext, IProjectTreeCustomizablePropertyValues propertyValues) in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\AbstractSpecialFolderProjectTreePropertiesProvider.cs:line 60
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.ApplyPropertiesProviderExtensions(IProjectTreeCustomizablePropertyContext context, IProjectTreeCustomizablePropertyValues values) in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\PhysicalProjectTreeProvider.cs:line 4890
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.ConstructProjectTree(PendingFolder folder, String fullPath, String projectRelativePath, ConfiguredProjectExports configuredProjectExports, ProjectTreeFlags parentFlags, CancellationToken cancellationToken) in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\PhysicalProjectTreeProvider.cs:line 2055
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken) in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\PhysicalProjectTreeProvider.cs:line 1827
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<GenerateOriginalTreeAsync>d__101.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\PhysicalProjectTreeProvider.cs:line 807
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 1025
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass95_0.<<Initialize>b__1>d.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass102_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 703
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass114_0.<<SubmitTreeUpdateHelperAsync>b__0>d.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 934
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass102_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 703
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.ProjectSystem.AppDesignerFolderProjectTreePropertiesProvider.AreContentsVisibleOnlyInShowAllFiles(IImmutableDictionary`2 projectTreeSettings) in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\AppDesignerFolderProjectTreePropertiesProvider.cs:line 83
   at Microsoft.VisualStudio.ProjectSystem.AbstractSpecialFolderProjectTreePropertiesProvider.CalculatePropertyValues(IProjectTreeCustomizablePropertyContext propertyContext, IProjectTreeCustomizablePropertyValues propertyValues) in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\AbstractSpecialFolderProjectTreePropertiesProvider.cs:line 60
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.ApplyPropertiesProviderExtensions(IProjectTreeCustomizablePropertyContext context, IProjectTreeCustomizablePropertyValues values) in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\PhysicalProjectTreeProvider.cs:line 4890
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.ConstructProjectTree(PendingFolder folder, String fullPath, String projectRelativePath, ConfiguredProjectExports configuredProjectExports, ProjectTreeFlags parentFlags, CancellationToken cancellationToken) in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\PhysicalProjectTreeProvider.cs:line 2055
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken) in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\PhysicalProjectTreeProvider.cs:line 1827
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<GenerateOriginalTreeAsync>d__101.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.Implementation\Designers\PhysicalProjectTreeProvider.cs:line 807
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 1025
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass95_0.<<Initialize>b__1>d.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 464
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass102_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 703
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass114_0.<<SubmitTreeUpdateHelperAsync>b__0>d.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 934
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.<>c__DisplayClass102_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext() in C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\ProjectTree\Providers\ProjectTreeProviderBase.cs:line 703<---

===================

```

**Comment by davkean** [comment]
@srivatsn This might affect shared projects when we are turned on.

**Comment by davkean** [comment]
I've not seen this for over 6 months, I think CPS made a fix around this a while back. I'll reopen it if I see it again.
