### ISSUE TITLE
Attempting to open resx on .NET Core displays an error

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#419]
![image](https://cloud.githubusercontent.com/assets/1103906/18107747/1380350e-6ebe-11e6-96bf-1c7b796b988d.png)

**Comment by 333fred** [comment]
```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETCoreApp,Version=v1.0'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsFrameworkMultiTargeting globalAssemblyResolution, String targetMoniker, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsFrameworkMultiTargeting globalAssemblyResolution, String targetMoniker, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsFrameworkMultiTargeting targetInfo, IDesignTimeAssemblyLoader assemblyLoader, String targetMoniker, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetGlobalTargetFrameworkProvider(IServiceProvider provider)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceAdded(Reference r)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceAdded(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Could not resolve mscorlib for target framework '.NETCoreApp,Version=v1.0'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse..ctor(IDesignTimeAssemblyLoader assemblyLoader, IVsFrameworkMultiTargeting globalAssemblyResolution, String targetMoniker, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.GetUniverse(IDesignTimeAssemblyLoader assemblyLoader, IVsFrameworkMultiTargeting globalAssemblyResolution, String targetMoniker, IVsSmartOpenScope dispenser)
   at Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkProvider..ctor(IVsFrameworkMultiTargeting targetInfo, IDesignTimeAssemblyLoader assemblyLoader, String targetMoniker, TypeDescriptionProvider parentProvider, IVsSmartOpenScope openScope)
   at Microsoft.VisualStudio.ProjectUtilities.GetGlobalTargetFrameworkProvider(IServiceProvider provider)
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.get_TypeProvider()
   at Microsoft.VisualStudio.Design.VSTypeResolutionService.VSLangProj._dispReferencesEvents.ReferenceAdded(Reference r)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAVSReferences.OnReferenceAdded(Reference reference)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ReferencesHostBridge.ApplyAsync(ReferencesDelta value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_1.<<InitializeCoreAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectHostBridge`3.<>c__DisplayClass36_0.<<InitializeCoreAsync>b__2>d.MoveNext()<---

===================
```

**Comment by 333fred** [comment]
Alright, I've determined what's causing the issue here. https://github.com/dotnet/roslyn-project-system/blob/184c8844b7954c16b61a3b0c93c6bce723e89019/src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorDesignerLoader.vb#L119 is attempting to create a MultiTargetLoader, which attempts to resolve mscorlib for the string `".NETCoreApp,Version=v1.0"`. This throws an InvalidOperationException in `VsTargetFrameworkUniverse`, as it can't find an mscorlib.

**Comment by 333fred** [comment]
Fixed in #687. Follow-up work is tracked by #686.

**Comment by jinujoseph** [comment]
I am seeing this still in latest build .

**Comment by jinujoseph** [comment]
i beleive https://github.com/dotnet/roslyn-project-system/pull/1060 this should address this.

**Comment by davkean** [comment]
Depends on what you're seeing. This issue is tracking 2 or 3 bugs. Can you open a new one with the underlying issue you are seeing?

**Comment by davkean** [comment]
Oh - I see your image now, sorry - yes this particular error will be fixed by my change, but the question is whether things are still broken after that though.
