### ISSUE TITLE
[Flaky Test] DependenciesGraphProvider_GetChildrenAsync fails with no source changes

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-project-system#431]
```
16:20:22 D:\j\workspace\windows_relea---c9724ea3\build\build.proj(80,5): error :     DependenciesGraphProvider_GetChildrenAsync [FAIL]
16:20:22         Assert.Equal() Failure
16:20:22         Expected: 1
16:20:22         Actual:   0
16:20:22         Stack Trace:
16:20:22           D:\j\workspace\windows_relea---c9724ea3\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\DependenciesGraphProviderTests.cs(195,0): 
                   at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesGraphProviderTests.<DependenciesGraphProvider_GetChildrenAsync>d__3.MoveNext()
16:20:22           --- End of stack trace from previous location where exception was thrown ---
16:20:22              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:20:22              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:20:22           --- End of stack trace from previous location where exception was thrown ---
16:20:22              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:20:22              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:20:22           --- End of stack trace from previous location where exception was thrown ---
16:20:22              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:20:22              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by jmarolf** [comment]
Also, should probably add a message to this assert so it clear from the failure what went wrong

**Comment by davkean** [comment]
tag @abpiskunov

**Comment by 333fred** [comment]
Had another failure on Jenkins: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn-project-system/job/master/job/windows_release_prtest/384/console

**Comment by 333fred** [comment]
PR #467

**Comment by davkean** [comment]
This is still failing: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn-project-system/job/master/job/windows_release_prtest/396/artifact/bin/Release/Tests/TestResults.html.

**Comment by davkean** [comment]
This this again: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn-project-system/job/master/job/windows_release_prtest/431/
