### ISSUE TITLE
Another CPS fault in the StartupProjectRegistrar 

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#515]
Opening a project sometimes results in this:

```
9/27/2016 6:11:35 PM
Recoverable
System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<Microsoft-VisualStudio-ProjectSystem-IProjectCapabilitiesScopeContext-ReloadIfNecessaryAsync>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScope.<PrepareNewCapabilitiesSnapshotAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScopeBase.<ProcessNewCapabilitiesAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.<GetLatestVersionAsync>d__39`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.<GetLatestVersionAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<LoadConfiguredProjectAsync>d__137.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<GetSuggestedConfiguredProjectAsync>d__149.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ActiveConfiguredProjectImpl`1.<>c__DisplayClass15_0.<<Initialize>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ActiveConfiguredProjectImpl`1.Initialize()
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.EnsureInitialized(Boolean allowInitializing)
   at Microsoft.VisualStudio.ProjectSystem.ActiveConfiguredProjectImpl`1.get_Value()
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectCommonServices.get_ActiveConfiguredProjectProperties()
   at Microsoft.VisualStudio.ProjectSystem.VS.UnconfiguredProjectVsServices.get_ActiveConfiguredProjectProperties()
   at Microsoft.VisualStudio.ProjectSystem.VS.Debug.StartupProjectRegistrar.<InitializeCoreAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Debug.StartupProjectRegistrar.<OnProjectFactoryCompletedAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__8_0>d.MoveNext()
```

**Comment by davkean** [comment]
Hmm, I do wonder what's causing capabilities to change - it looks like the active configured project hasn't been initialized at this point? Which is very strange given this is after the project is considered loaded and well after the active configured project has loaded. Also we would have not been initialized in the first place - because C#/VB capability don't get promoted into unconfigured project until _after_ the first configured project has been loaded.

**Comment by mavasani** [comment]
+1 I hit the same now.

**Comment by abpiskunov** [comment]
Just saw that again with d15prerel 25818.4

**Comment by basoundr** [comment]
We have not seen this in a while. I am going to close this for now. @srivatsn is there reports of people seeing this now?

**Comment by srivatsn** [comment]
Yes this seems to happen every so often still.

**Comment by basoundr** [comment]
With the current state of the project, where the SDK tooling is present in the machine before loading the project, we are not going to see dynamic change in capabilities.

Although, in the future, we could have a different tooling story, where the above statement could be false. In that case, the components that are loaded and unloaded based on the capabilities should move over to `ProjectDynamicLoadComponent`.

For now, I am closing this issue since we are not running into this issue.

**Comment by davkean** [comment]
What if I change the Sdk element of my project?
