### ISSUE TITLE
LanguageService is crashing with ActiveProjectConfigurationChangedException when publishing tree

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#521]
Hit this while debugging, this is happening when we publish the tree:

-		$exception	{"Exception of type 'Microsoft.VisualStudio.ProjectSystem.ActiveProjectConfigurationChangedException' was thrown."}	Microsoft.VisualStudio.ProjectSystem.ActiveProjectConfigurationChangedException

```
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.UnconfiguredProjectHostBridge`3.<>c__DisplayClass19_0.<ApplyAsync>b__0(TApplied value)
   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.<>c__DisplayClass28_0`1.<GetSpecificVersionAsync>b__0(T s)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.UnconfiguredProjectHostBridge`3.<ApplyAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.<PublishTreeAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.Handlers.SourceItemHandler.<HandleAsync>d__11.MoveNext() in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\LanguageServices\Handlers\SourceItemHandler.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost.<HandleAsync>d__16.MoveNext() in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\LanguageServices\LanguageServiceHost.cs:line 122

**Comment by mavasani** [comment]
I am also hitting this very often while debugging.
