### ISSUE TITLE
Expanding Dependencies node causes an assert

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#560]
```
CPS Error: 0 : HResult.Invoke caught the following exception: Microsoft.Assumes+InternalErrorException: Not a project item.
   at Microsoft.Assumes.Fail(String message, Boolean showAssert)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.get_ProjectPropertiesContext()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.FindMatchedOAVSReference()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.Initialize()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode.EnsureInitialized()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.get_AutomationObject()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass628_0.<<GetProperty>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass550_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
CPS Error: 0 : HResult.Invoke caught the following exception: Microsoft.Assumes+InternalErrorException: Not a project item.
   at Microsoft.Assumes.Fail(String message, Boolean showAssert)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.get_ProjectPropertiesContext()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.FindMatchedOAVSReference()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.Initialize()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode.EnsureInitialized()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.get_AutomationObject()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass628_0.<<GetProperty>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass550_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)

```

**Comment by abpiskunov** [comment]
@davkean  what was your scenario? What node did you expand?

**Comment by abpiskunov** [comment]
@davkean  i can not repro it. I assume you expanded the top Dependencies node. At what stage did you do it? During project load or when project was loaded and restored? Was it a web app with Bower packages? Did project have Analyzers node?

**Comment by abpiskunov** [comment]
please reopen if you can recall repro steps or see it again.
