### ISSUE TITLE
Attempting to create a resources file results in a project fault

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#576]
1. Create new .NET Core proejct
2. Properties -> Resources
3. Click "This project does not contain a default resources file, Click here to create one."

![image](https://cloud.githubusercontent.com/assets/1103906/19209584/139bc1c6-8cc2-11e6-80e6-f5eb6a9af2ff.png)

```
=====================
10/7/2016 7:05:41 PM
Recoverable
System.ArgumentException: Zero length files array
Parameter name: files
   at Microsoft.Requires.Argument(Boolean condition, String parameterName, String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<AddItemWithSpecificAsync>d__591.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass461_0.<<AddItemWithSpecific>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass550_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
===================
10/7/2016 7:12:10 PM
Recoverable
System.ArgumentException: Zero length files array
Parameter name: files
   at Microsoft.Requires.Argument(Boolean condition, String parameterName, String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<AddItemWithSpecificAsync>d__591.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass461_0.<<AddItemWithSpecific>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass550_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
===================
```

Followed by an assert:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
CreateNewSpecialFile

Exception: System.ArgumentException: Could not find the file 'C:\Users\davkean\documents\visual studio 15\Projects\ConsoleApplication34\ConsoleApplication34\ConsoleApplication34.csproj\Resources.resx'.

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerPanel.CreateDesigner()

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerPanel.ShowDesigner(Boolean Show)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerPanel.set_CustomViewProvider(CustomViewProvider value)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.SpecialFileCustomView.CreateNewSpecialFile()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)



   at Microsoft.VisualStudio.Editors.AppDesCommon.Utils.ReportWithoutCrash(Exception ex, String exceptionEventDescription, String throwingComponentName)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.SpecialFileCustomView.CreateNewSpecialFile()

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerPanel.CreateDesigner()

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerPanel.ShowDesigner(Boolean Show)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerPanel.set_CustomViewProvider(CustomViewProvider value)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.SpecialFileCustomView.CreateNewSpecialFile()

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.SpecialFileCustomView.LinkLabel_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)

   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)

   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.Label.WndProc(Message& m)

   at System.Windows.Forms.LinkLabel.WndProc(Message& msg)

   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)

   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

Follow by 

```
---------------------------
Microsoft Visual Studio
---------------------------
Could not find the file 'C:\Users\davkean\documents\visual studio 15\Projects\ConsoleApplication34\ConsoleApplication34\ConsoleApplication34.csproj\Resources.resx'.
---------------------------
OK   
---------------------------
```

**Comment by davkean** [comment]
This looks to be something in CPS.

**Comment by srivatsn** [comment]
@333fred I assume this doesn't repro anymore since you were able to get the designer to show up?

**Comment by 333fred** [comment]
Yeah, I'm not able to repro this on d15rel 25831.01. Reopen if we see again.

**Comment by davkean** [comment]
I think this was a CPS bug that they might have fixed, @jviau does this ring a bell?

**Comment by jviau** [comment]
I don't recall CPS doing anything to fix this issue. I tested it on a build from last week and I get this error instead:
![resxerror](https://cloud.githubusercontent.com/assets/5439812/20289313/181df2ca-aa8e-11e6-847d-f3d420bb020f.png)

**Comment by davkean** [comment]
Thanks @jviau, @333fred found the cause and will have fix out tomorrow.
