### ISSUE TITLE
Create ASP.NET Core Web Application in VS twice produces a CPS fault dialog.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#630]
Ported from TFS:

INSTALL STEPS

1.Clean Win10 x64 ENU machine

2.run command 

net stop wuauserv

sc config wuauserv start=Disabled
1. Run preinstall.cmd
2. Install WPT.25813.01
3. Add private MyGet feeds in Package Manager Settings dialog

6.After installing VS, apply this regkey fix for Package Restore to work.

REPRO STEPS 

1.Open VS -File > New Project > ASP.NET Core Web Application with web application 

2.Do not close the VS , do step1 again

3.Build the project . 

Will meet the warning. 'The project system has encountered and error' object reference not set to an instance of an object.

---

Comment from @mlorbetske

It looks like the issue is happening here:

```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.ProjectExternalErrorReporter.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.Microsoft.VisualStudio.Shell.Interop.IVsLanguageServiceBuildErrorReporter2.ReportError2(String bstrErrorMessage, String bstrErrorId, VSTASKPRIORITY nPriority, Int32 iStartLine, Int32 iStartColumn, Int32 iEndLine, Int32 iEndColumn, String bstrFileName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Build.LanguageServiceErrorListProvider.<AddMessageCoreAsync>d__9.MoveNext()
```

**Comment by basoundr** [comment]
Does not repro in 26020.0.d15prerel. Closing this issue. Please reopen with updated stack trace if it repro-es again.
