### ISSUE TITLE
Changing any assembly properties causes VS to crash

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#762]
1. File -> New -> .NET Core console app
2. Right-click Properties -> Application -> Assembly Info
3. Change Title to "Foo"
4. Click OK

--Crash--

**Comment by davkean** [comment]
Here's what I got before VS crashed:

```
System.ArgumentException: Zero length files array
Parameter name: files
   at Microsoft.Requires.Argument(Boolean condition, String parameterName, String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<AddItemWithSpecificAsync>d__591.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass461_0.<<AddItemWithSpecific>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass550_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
```

**Comment by mavasani** [comment]
We are going to hide the AssemblyInformation button in Application page: https://github.com/dotnet/roslyn-project-system/issues/977. These properties can be correctly set in the Package property page.

**Comment by davkean** [comment]
If the code still exists that adds it to AssemblyInfo.cs, then this is still relavant.

**Comment by davkean** [comment]
Hmm, this might actually be the special files provider? Can you see if this repro's before you changes? As this will still be an issue if you remove the button.

**Comment by mavasani** [comment]
Thanks Dave. Yes, indeed setting the flag to emit the properties in AssemblyInfo causes the crash. Investigating further.

**Comment by jnm2** [comment]
If I want to set assembly info without creating a NuGet package, is the recommended way to add an `AssemblyInfo.cs` next to the .csproj? Or will something new happen, like putting the information inside the csproj?

**Comment by jnm2** [comment]
I'm getting CS0579 duplicate attribute errors for `AssemblyCompany`, `AssemblyProduct`, `AssemblyVersion`, `AssemblyInformationalVersion` and `AssemblyTitle`, but not for `AssemblyCopyright` or `ComVisible(false)`.

I'm not sure where else these could be defined though. The VS crashes if I change any of these in the app designer, and I don't see them in any file.

**Comment by paladin2005** [comment]
jnm2 I have same issue. The link you provide is not working. How I fix this?

**Comment by jnm2** [comment]
@paladin2005 Add `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` to your main property group.

**Comment by jnm2** [comment]
@paladin2005 Or, stop using AssemblyInfo.cs and use this goodness:

```c#
  <PropertyGroup>
    <Version>(Windows Explorer product version string)</Version>
    <AssemblyVersion>(Windows Explorer file version)</AssemblyVersion>
    <AssemblyTitle>(Windows Explorer file description)</AssemblyTitle>
    <Authors>(Windows Explorer company)</Authors>
    <Copyright>(Windows Explorer copyright)</Copyright>
  </PropertyGroup>
```

This also drives NuGet packages, so it merges the duplicated information into one place which I think is cool.

**Comment by paladin2005** [comment]
@jnm2 Tried with both and nothing. Still getting errors. My problem come when I do a publish (Release) or change target to Release. My temporal solution is delete BIN and OBJ folders from Library and Web projects. Make the publish and when I come back to debug came the same error... and same temporal solution.

**Comment by jnm2** [comment]
@paladin2005 Make sure you're adding this to an unconditional property group. Aside from that, nothing comes to mind without being able to see the csproj. If that doesn't work your best bet is to create a repro project.
