### ISSUE TITLE
Assert opening Advanced Build Settings

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#809]
Under Debug configuration:

1. Open Application Designer
2. Choose Build -> Advanced

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
GetCurrentProperty: Property was found in an open page, so this time the function will succeed.  However, the property was not found as a common property or a property on this page, so the same query would fail if the other page were not open.  This probably indicates an error in the caller.



   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.GetCurrentProperty(Int32 dispid, String PropertyName, Object& obj)
   at Microsoft.VisualStudio.Editors.PropertyPages.AdvBuildSettingsPropPage.IsExeProject()
   at Microsoft.VisualStudio.Editors.PropertyPages.AdvBuildSettingsPropPage.BaseAddressSet(Control control, PropertyDescriptor prop, Object value)
   at Microsoft.VisualStudio.Editors.PropertyPages.PropertyControlData.InitPropertyUI()
   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.InitPage()
   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.SetObjects(Object[] objects)
   at Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.ShowChildPage(String Title, Type PageType, String F1Keyword)
   at Microsoft.VisualStudio.Editors.PropertyPages.BuildPropPage.AdvancedButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by RaulPerez1** [comment]
Not reproing this anymore, most likely fixed by one of the other property page changes I have.
