### ISSUE TITLE
Unit tests are failing from Visual Studio due to missing "msbuild"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#815]
![image](https://cloud.githubusercontent.com/assets/1103906/20612735/07f91812-b311-11e6-85a9-d9e477ab0380.png)

They are failed with the following:

```
Test Name:	DebugTokenReplacer_ReplaceTokensInProfileTests
Test FullName:	Microsoft.VisualStudio.ProjectSystem.Debug.DebugTokenReplacerTests.DebugTokenReplacer_ReplaceTokensInProfileTests
Test Source:	C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\ProjectSystem\Debug\DebugTokenReplacerTests.cs : line 40
Test Outcome:	Failed
Test Duration:	0:00:00.156

Result StackTrace:	
at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReaderHelpers.ConfigurationFileMayHaveToolsets()
   at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader configurationReader, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetRegistryReader registryReader, ToolsetConfigurationReader configReader)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection.get_GlobalProjectCollection()
   at Microsoft.Build.Construction.ProjectRootElement.Create(XmlReader xmlReader)
   at Microsoft.VisualStudio.ProjectSystem.Debug.DebugTokenReplacerUnderTest.TestProjectReadAccessor.CreateMsBuildProject() in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\ProjectSystem\Debug\DebugTokenReplacerTests.cs:line 138
   at Microsoft.VisualStudio.ProjectSystem.Debug.DebugTokenReplacerUnderTest.TestProjectReadAccessor.GetProjectAsync() in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\ProjectSystem\Debug\DebugTokenReplacerTests.cs:line 112
   at Microsoft.VisualStudio.ProjectSystem.Debug.DebugTokenReplacer.<ReplaceTokensInStringAsync>d__9.MoveNext() in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Debug\DebugTokenReplacer.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.Debug.DebugTokenReplacer.<ReplaceTokensInProfileAsync>d__8.MoveNext() in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Debug\DebugTokenReplacer.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.Debug.DebugTokenReplacerTests.<DebugTokenReplacer_ReplaceTokensInProfileTests>d__3.MoveNext() in C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests\ProjectSystem\Debug\DebugTokenReplacerTests.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Shared.BuildEnvironmentHelper.Initialize()
   at Microsoft.Build.Shared.BuildEnvironmentHelper.BuildEnvironmentHelperSingleton..cctor()
Result Message:	
System.TypeInitializationException : The type initializer for 'BuildEnvironmentHelperSingleton' threw an exception.
---- System.InvalidOperationException : Could not determine a valid location to MSBuild. Try running this process from the Developer Command Prompt for Visual Studio.
```

**Comment by srivatsn** [comment]
Is this still happening?

**Comment by davkean** [comment]
This was caused by https://github.com/Microsoft/msbuild/issues/1456 and has since been fixed.
