### ISSUE TITLE
Flaky Test: DependenciesGraphProvider_TrackChangesAsync

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#837]
```
20:50:45 D:\j\workspace\windows_relea---f10b36dd\build\build.proj(81,5): error :     DependenciesGraphProvider_TrackChangesAsync [FAIL]
20:50:45         Assert.Equal() Failure
20:50:45         Expected: 1
20:50:45         Actual:   0
20:50:45         Stack Trace:
20:50:45           D:\j\workspace\windows_relea---f10b36dd\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\ProjectSystem\VS\Tree\Dependencies\DependenciesGraphProviderTests.cs(490,0): at Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesGraphProviderTests.<DependenciesGraphProvider_TrackChangesAsync>d__8.MoveNext()
20:50:45           --- End of stack trace from previous location where exception was thrown ---
20:50:45              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
20:50:45              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
20:50:45           --- End of stack trace from previous location where exception was thrown ---
20:50:45              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
20:50:45              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
20:50:45           --- End of stack trace from previous location where exception was thrown ---
20:50:45              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
20:50:45              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
PR Link: https://github.com/dotnet/roslyn-project-system/pull/835
Jenkins Link: https://ci.dot.net/job/dotnet_roslyn-project-system/job/dev15-rc2/job/windows_release_prtest/1/

@abpiskunov

**Comment by mavasani** [comment]
This failed the signed build as well: https://devdiv.visualstudio.com/DevDiv/_build?buildId=456805

@abpiskunov can you please investigate?

**Comment by mavasani** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn-project-system/job/master/job/vsi/42/console

**Comment by 333fred** [comment]
Another failure: https://ci.dot.net/job/dotnet_roslyn-project-system/job/master/job/windows_release_prtest/117/console. @abpiskunov
