### ISSUE TITLE
Migration Throws "Object reference Exception " 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#896]
**Repro Steps**

- Copy the project from \\scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip
- Unzip to your machine
- open the VSMigrationDemo\VSMigrationDemo.sln file 
- Accept all the migration notification.

**Expected**
Project migrated successfully

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/20980234/96fb7c88-bc64-11e6-83ca-abf402ac6e77.png)

Log says 

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<<get_IsSolutionFullyLoaded>b__67_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.get_IsSolutionFullyLoaded()
   at NuGet.PackageManagement.VisualStudio.SolutionRestoreWorker.<ScheduleRestoreAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<<get_IsSolutionFullyLoaded>b__67_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.get_IsSolutionFullyLoaded()
   at NuGet.PackageManagement.VisualStudio.SolutionRestoreWorker.<ScheduleRestoreAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

**Found in Build**
d15rel/15.0.26006.0

**Comment by srivatsn** [comment]
Tagging @rrelyea and @alpaix since this seems to be in `NuGet.PackageManagement.VisualStudio.SolutionRestoreWorker`

**Comment by rrelyea** [comment]
Should we consider this an RC2 or RC3 issue?

**Comment by rrelyea** [comment]
Port to https://github.com/NuGet/Home/issues/4067
Feel free to close this issue. Please do answer the RC2 v RC3 question.

**Comment by srivatsn** [comment]
Communicated risk with Rob. Closing this since we are tracking the issue on NuGet.
