### ISSUE TITLE
(d15prerel) Creating Net Core projects crashes VS

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#931]
**Repro Steps**
-Create Console App (.Net Core ) 

**Expected**
Project created successfully 

**Actual**

![image](https://cloud.githubusercontent.com/assets/12449387/21131429/771d7f70-c0c3-11e6-9203-31f0aada7654.png)

Dmp file : \\mlangfs1\public\Jinuj\dmp\CreateCoreProject.dmp

![image](https://cloud.githubusercontent.com/assets/12449387/21131500/ddae935a-c0c3-11e6-87ee-3359e8db14d4.png)

System.ArgumentException occurred
  HResult=0x80070057
  Message='path' cannot be an empty string ("") or start with the null character.
  Source=Microsoft.VisualStudio.Validation
  StackTrace:
   at Microsoft.Requires.NotNullOrEmpty(String value, String parameterName) in D:\A\_work\6\s\src\Microsoft.VisualStudio.Validation.Shared\Requires.cs:line 145
   at Microsoft.VisualStudio.ProjectSystem.PathHelper.MakeRooted(UnconfiguredProject unconfiguredProject, String path) in F:\A\_work\12\s\src\Microsoft.VisualStudio.ProjectSystem\Utilities\PathHelper.cs:line 364
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher.<GetProjectLockFilePathAsync>d__12.MoveNext() in E:\A\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\ProjectLockFileWatcher.cs:line 103
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at Microsoft.VisualStudio.ProjectSystem.VS.ProjectLockFileWatcher.<ProjectTree_ChangedAsync>d__11.MoveNext() in E:\A\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\ProjectLockFileWatcher.cs:line 78
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\AsyncMethodBuilder.cs:line 1034
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state) in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 1273
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 954
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 901
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 1250
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 819
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 1161

**Found in** 
![image](https://cloud.githubusercontent.com/assets/12449387/21131515/f4eab80a-c0c3-11e6-8c85-162814bc890e.png)

**Comment by davkean** [comment]
Dup of this: https://github.com/dotnet/roslyn-project-system/issues/921
